server:
  port: 8080
  servlet:
    context-path: /zk-admin
    session:
      timeout: 1d
spring:
  datasource:
    url: jdbc:h2:file:~/.h2/zk_admin;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: root
    password: root
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  thymeleaf:
    enabled: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
    cache: false
  transaction:
    default-timeout: 60s
    rollback-on-commit-failure: true
curator:
  client:
    base-sleep-time-ms: 6000
    session-timeout-ms: 10000
    connection-timeout-ms: 10000
    max-retries: 5
logging:
  level:
    cn.zk: info
    org.apache.curator: debug
